package com.hbmtools.entities;
// Generated 17-May-2021, 8:02:28 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * BikeRental generated by hbm2java
 */
public class BikeRental implements java.io.Serializable {

	private Integer bikeRentalNo;
	private Bike bike;
	private Customer customer;
	private Date rentedDt;
	private int duration;
	private float amountPaid;

	public BikeRental() {
	}

	public BikeRental(Bike bike, Customer customer, Date rentedDt, int duration, float amountPaid) {
		this.bike = bike;
		this.customer = customer;
		this.rentedDt = rentedDt;
		this.duration = duration;
		this.amountPaid = amountPaid;
	}

	public Integer getBikeRentalNo() {
		return this.bikeRentalNo;
	}

	public void setBikeRentalNo(Integer bikeRentalNo) {
		this.bikeRentalNo = bikeRentalNo;
	}

	public Bike getBike() {
		return this.bike;
	}

	public void setBike(Bike bike) {
		this.bike = bike;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getRentedDt() {
		return this.rentedDt;
	}

	public void setRentedDt(Date rentedDt) {
		this.rentedDt = rentedDt;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public float getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(float amountPaid) {
		this.amountPaid = amountPaid;
	}

}
