package com.hbmtools.entities;
// Generated 17-May-2021, 8:02:28 AM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Bike generated by hbm2java
 */
public class Bike implements java.io.Serializable {

	private Integer bikeNo;
	private String bikeModelNm;
	private String manufacturer;
	private String rtaRegistrationNo;
	private float price;
	private Set bikeRentals = new HashSet(0);

	public Bike() {
	}

	public Bike(String bikeModelNm, String manufacturer, String rtaRegistrationNo, float price) {
		this.bikeModelNm = bikeModelNm;
		this.manufacturer = manufacturer;
		this.rtaRegistrationNo = rtaRegistrationNo;
		this.price = price;
	}

	public Bike(String bikeModelNm, String manufacturer, String rtaRegistrationNo, float price, Set bikeRentals) {
		this.bikeModelNm = bikeModelNm;
		this.manufacturer = manufacturer;
		this.rtaRegistrationNo = rtaRegistrationNo;
		this.price = price;
		this.bikeRentals = bikeRentals;
	}

	public Integer getBikeNo() {
		return this.bikeNo;
	}

	public void setBikeNo(Integer bikeNo) {
		this.bikeNo = bikeNo;
	}

	public String getBikeModelNm() {
		return this.bikeModelNm;
	}

	public void setBikeModelNm(String bikeModelNm) {
		this.bikeModelNm = bikeModelNm;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getRtaRegistrationNo() {
		return this.rtaRegistrationNo;
	}

	public void setRtaRegistrationNo(String rtaRegistrationNo) {
		this.rtaRegistrationNo = rtaRegistrationNo;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public Set getBikeRentals() {
		return this.bikeRentals;
	}

	public void setBikeRentals(Set bikeRentals) {
		this.bikeRentals = bikeRentals;
	}

}
