package com.hbmtools.entities;
// Generated 17-May-2021, 8:02:28 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer customerNo;
	private String fullNm;
	private Date dob;
	private String gender;
	private String mobileNo;
	private String emailAddress;
	private String drivingLicenseNo;
	private Set bikeRentals = new HashSet(0);

	public Customer() {
	}

	public Customer(String fullNm, Date dob, String gender, String mobileNo, String emailAddress) {
		this.fullNm = fullNm;
		this.dob = dob;
		this.gender = gender;
		this.mobileNo = mobileNo;
		this.emailAddress = emailAddress;
	}

	public Customer(String fullNm, Date dob, String gender, String mobileNo, String emailAddress,
			String drivingLicenseNo, Set bikeRentals) {
		this.fullNm = fullNm;
		this.dob = dob;
		this.gender = gender;
		this.mobileNo = mobileNo;
		this.emailAddress = emailAddress;
		this.drivingLicenseNo = drivingLicenseNo;
		this.bikeRentals = bikeRentals;
	}

	public Integer getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(Integer customerNo) {
		this.customerNo = customerNo;
	}

	public String getFullNm() {
		return this.fullNm;
	}

	public void setFullNm(String fullNm) {
		this.fullNm = fullNm;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getDrivingLicenseNo() {
		return this.drivingLicenseNo;
	}

	public void setDrivingLicenseNo(String drivingLicenseNo) {
		this.drivingLicenseNo = drivingLicenseNo;
	}

	public Set getBikeRentals() {
		return this.bikeRentals;
	}

	public void setBikeRentals(Set bikeRentals) {
		this.bikeRentals = bikeRentals;
	}

}
