package com.hbmtools.entities;
// Generated 17-May-2021, 8:02:28 AM by Hibernate Tools 5.4.7.Final

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private int staffNo;
	private String fullNm;
	private Integer age;
	private String gender;
	private Integer experience;
	private String mobileNbr;
	private String emailAddress;

	public Staff() {
	}

	public Staff(int staffNo) {
		this.staffNo = staffNo;
	}

	public Staff(int staffNo, String fullNm, Integer age, String gender, Integer experience, String mobileNbr,
			String emailAddress) {
		this.staffNo = staffNo;
		this.fullNm = fullNm;
		this.age = age;
		this.gender = gender;
		this.experience = experience;
		this.mobileNbr = mobileNbr;
		this.emailAddress = emailAddress;
	}

	public int getStaffNo() {
		return this.staffNo;
	}

	public void setStaffNo(int staffNo) {
		this.staffNo = staffNo;
	}

	public String getFullNm() {
		return this.fullNm;
	}

	public void setFullNm(String fullNm) {
		this.fullNm = fullNm;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getExperience() {
		return this.experience;
	}

	public void setExperience(Integer experience) {
		this.experience = experience;
	}

	public String getMobileNbr() {
		return this.mobileNbr;
	}

	public void setMobileNbr(String mobileNbr) {
		this.mobileNbr = mobileNbr;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
