package com.hbmtools.entities;
// Generated 17-May-2021, 8:02:28 AM by Hibernate Tools 5.4.7.Final

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private int storeNo;
	private String storeNm;
	private String contactNo;
	private String emailAddress;
	private String address;
	private String city;
	private String state;
	private Integer zip;
	private String country;

	public Store() {
	}

	public Store(int storeNo) {
		this.storeNo = storeNo;
	}

	public Store(int storeNo, String storeNm, String contactNo, String emailAddress, String address, String city,
			String state, Integer zip, String country) {
		this.storeNo = storeNo;
		this.storeNm = storeNm;
		this.contactNo = contactNo;
		this.emailAddress = emailAddress;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
	}

	public int getStoreNo() {
		return this.storeNo;
	}

	public void setStoreNo(int storeNo) {
		this.storeNo = storeNo;
	}

	public String getStoreNm() {
		return this.storeNm;
	}

	public void setStoreNm(String storeNm) {
		this.storeNm = storeNm;
	}

	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
